### ISSUE TITLE
Live Stream Stabilization

### ISSUE THREAD

**Issue by canozcivelek** [AIHunters/EvenVizion#2]
Hi!
I want to stabilize a real-time RTSP stream, so I don't need any video files for input or output. I have a working Gstreamer pipeline to make stream happen. How should I integrate Evenvizion into my project? Also I wasn't able to pip install Evenvizion. I have OpenCV 4 with Contrib on my device, could that be a problem (OpenCV 4 instead of 3.x as stated in requirements.txt)? If so, should I build it from source or something?

Thanks!

**Comment by dianaK-oss** [comment]
Hi!

You can't install evenvizion package by pip because you have OpenCV4, you should install version from requirements.

About stream processing, could you specify what type of stabilization do you want to get? 
Do you want to get stabilization relative to the first frame (as in our case, the first frame is the origin) or consider the location only relative to the previous one

**Comment by canozcivelek** [comment]
Hi, Location to previous one would make more sense in my case. I want to equalize minor vibrations that occur while streaming.

**Comment by dianaK-oss** [comment]
Yo can check the file: https://github.com/AIHunters/EvenVizion/blob/master/evenvizion/examples/evenvizion_component.py
and find an example of how to use the package.
You don't really need to analyze the video, but just to feed the system with two frames sequentially and search for the homography matrix between them and stabilize your picture.

Code example:

#calculate homography matrix:
```
frame_processing_a = FrameProcessing(image_a)
key_points_a, key_points_b = \
                frame_processing_b.concatenate_all_features_types(frame_processing_a)
matrix_H = compute_homography(key_points_a, key_points_b)
```

#redraw the frame in a new position. Note, if you want to calculate the optimal background, where you will draw a stabilized frame, you should form a dictionary with homography matrices.
```
homography_dict={1: matrix_H}
corner_dict = evenvizion.visualization.stabilization.get_reference_system(homography_dict)
background = evenvizion.visualization.stabilization.initialize_background(image_b, width, corner_dict)
stabilize_frame, _ = evenvizion.visualization.stabilization.stabilize_view(image_b, matrix_H, background, corner_dict, width)
```


So you get a stabilized frame:)

**Comment by canozcivelek** [comment]
Hi,

Thank you very much for the detailed explanation. I will try it out and see if I can manage to pull it off. Thanks again for your time. Though I didn't understand what you meant on that last sentence :/

**Comment by dianaK-oss** [comment]
Еhanks for your interest! By PR I meant pull request here :) Please let me know if you have any other questions
